### ISSUE TITLE
可否增加一些自定义功能？

### ISSUE THREAD

**Issue by lxt20180608** [7Sageer/sublink-worker#1]
如远程配置文件可自选

**Comment by 7Sageer** [comment]
感谢您的反馈和建议。现在已经有实现这个想法的计划了。

这个项目最初是给我自用的，所以在实现时并没有考虑太多自定义的功能。要实现这部分功能可能需要进行一些重构，这可能会耗费一些时间——我会在有空的时候进行推进。

如果您有兴趣，也欢迎提交PR来实现您期望的功能。

再次感谢您的贡献!

**Comment by kwxmxb** [comment]
> 感谢您的反馈和建议。现在已经有实现这个想法的计划了。
> 
> 这个项目最初是给我自用的，所以在实现时并没有考虑太多自定义的功能。要实现这部分功能可能需要进行一些重构，这可能会耗费一些时间——我会在有空的时候进行推进。
> 
> 如果您有兴趣，也欢迎提交PR来实现您期望的功能。
> 
> 再次感谢您的贡献!

可以增加一个负载均衡或者故障转移规则，主要是适用于不同网络下的，比如代理网络下，因为，有一些代理网络可能IP不固定

**Comment by kwxmxb** [comment]
> > 感谢您的反馈和建议。现在已经有实现这个想法的计划了。
> > 这个项目最初是给我自用的，所以在实现时并没有考虑太多自定义的功能。要实现这部分功能可能需要进行一些重构，这可能会耗费一些时间——我会在有空的时候进行推进。
> > 如果您有兴趣，也欢迎提交PR来实现您期望的功能。
> > 再次感谢您的贡献!
> 
> 可以增加一个负载均衡或者故障转移规则，主要是适用于不同网络下的，比如代理网络下，因为，有一些代理网络可能IP不固定

部署方法存在问题，跳转之后授权报错返回错误

**Comment by 7Sageer** [comment]
> 部署方法存在问题，跳转之后授权报错返回错误

感谢提醒，今天早上使用kv替代r2后没有进行详细测试导致部署脚本存在一些缺陷，目前应该已经修复了。请拉取最新版本再次尝试部署。如果有问题，欢迎继续反馈。

**Comment by kwxmxb** [comment]
> > 部署方法存在问题，跳转之后授权报错返回错误
> 
> 感谢提醒，今天早上使用kv替代r2后没有进行详细测试导致部署脚本存在一些缺陷，目前应该已经修复了。请拉取最新版本再次尝试部署。如果有问题，欢迎继续反馈。

我好像发现clash 订阅转换之后，它无法识别到，clash meta 安卓版用链接的形式无法远程下载配置文件，但是本地文件好像能用，我也不知道什么原因
节点之间转换是否支持链接形式，还是只支持自己创建节点格式呢？

**Comment by 7Sageer** [comment]
> 我好像发现clash 订阅转换之后，它无法识别到，clash meta 安卓版用链接的形式无法远程下载配置文件，但是本地文件好像能用，我也不知道什么原因 节点之间转换是否支持链接形式，还是只支持自己创建节点格式呢？

我推测你可能直接使用了worker的域名（例如示例站点），这在中国大陆无法直接访问。如果是这样，你可以使用代理导入配置文件。或者给worker绑定自己的域名。
