### ISSUE TITLE
请求支持KV命令空间

### ISSUE THREAD

**Issue by hn315** [7Sageer/sublink-worker#13]
没有开通存储桶，谢谢

**Comment by 7Sageer** [comment]
感谢反馈，我最近也在考虑使用kv替代R2，目前主要考虑的是向后兼容之前部署的版本。在此之前，欢迎访问https://sublink-worker.seven7-ade.workers.dev/ 体验Sublink Worker。

**Comment by hn315** [comment]
> 感谢反馈，我最近也在考虑使用kv替代R2，目前主要考虑的是向后兼容之前部署的版本。在此之前，欢迎访问https://sublink-worker.seven7-ade.workers.dev/ 体验Sublink Worker。

没信用卡开不了存储桶，一直在找一个优秀的自部署订阅转换工具，我在用openclash，也试过sub-store 总是没有一个符合自己要求的，期待作者的作品。就像肥羊大佬的在线转换一样，前端接受各种订阅链接（有base64编码的，也有text文件的）、单个节点，支持clash 远端配置，像肥羊转换后端一样顿转换出订阅。关注和期待作者。

**Comment by 7Sageer** [comment]
已经使用kv替代R2，请拉取最新版本部署即可。
