### ISSUE TITLE
能否新增固定的规则模板

### ISSUE THREAD

**Issue by zscontinent** [7Sageer/sublink-worker#14]
请问能否新增固定的规则模板？
比如ACL4SSR之类的固定规则模板，因为经常会使用到，但这边似乎没法增加相应的模板

**Comment by 7Sageer** [comment]
感谢反馈，你可以打开`advanced option`中直接勾选`comprehensive`来获得类似的体验。如果这不能满足你的需求，请务必告知我如何进行改进。

**Comment by zscontinent** [comment]
> 感谢反馈，你可以打开`advanced option`中直接勾选`comprehensive`来获得类似的体验。如果这不能满足你的需求，请务必告知我如何进行改进。

类似于图中的这种规则模板
![Uploading 捕获.PNG…]()

**Comment by zscontinent** [comment]
> 感谢反馈，你可以打开`advanced option`中直接勾选`comprehensive`来获得类似的体验。如果这不能满足你的需求，请务必告知我如何进行改进。

![捕获](https://github.com/user-attachments/assets/6320d0a1-f036-4491-a646-533cfe6869c7)
类似于图中这种规则模板

**Comment by 7Sageer** [comment]
感谢您对项目的支持，目前暂时还没有计划实现这个功能。但如果您有兴趣，可以考虑提交PR来实现这个功能。如果您需要任何帮助，请随时与我联系。
