### ISSUE TITLE
导入BASE64加密的订阅链接时，中文字符似乎会显示乱码

### ISSUE THREAD

**Issue by Tobyyyyt** [7Sageer/sublink-worker#16]
导入BASE64加密的订阅链接时，中文字符似乎会显示为乱码

**Comment by Elegant-Westlord** [comment]
![Screenshot_2024-09-04-08-48-26-49_ed7cc6eecf382e65e95dbc137f8c2558](https://github.com/user-attachments/assets/6528115c-f936-4b2c-bbe7-7d669f774712)
这是转换后的效果，软件Flclash, 0.8.57

**Comment by gutaot** [comment]
从稳连云节点转换订阅链接后，这搞变成这样情况啊i![Screenshot_20240906-200538.png](https://github.com/user-attachments/assets/fbf31244-c47f-4107-b944-2dbc25d2ffbe)

**Comment by 7Sageer** [comment]
> 从稳连云节点转换订阅链接后，结果是变成这样情况啊!

这部分节点除了名字外是否连接正常？

**Comment by Elegant-Westlord** [comment]
> > 从稳连云节点转换订阅链接后，结果是变成这样情况啊!
> 
> 这部分节点除了名字外是否连接正常？

至少我的连接正常

**Comment by gutaot** [comment]
> > 从稳连云节点转换订阅链接后，结果是变成这样情况啊!
> 
> 这部分节点除了名字外是否连接正常？
> 
> 

连接正常啊，但是国家及地区国旗，就是显示乱码。

**Comment by 7Sageer** [comment]
已经尝试修复，请拉取最新版本

**Comment by gutaot** [comment]
> 已经尝试修复，请拉取最新版本

正常，没问题， 辛苦您啦！

**Comment by gutaot** [comment]
> 已经尝试修复，请拉取最新版本

正常，没问题，辛苦您啦！
