### ISSUE TITLE
github规则无效

### ISSUE THREAD

**Issue by Ocean-TXT** [7Sageer/sublink-worker#23]
情况是这样的，转换后，设置GitHub流量规则后，github也是走的微软服务的规则，并未走GitHub流量规则，查看日志显示 github网页是地址是github.githubassets.com走的微软服务规则，希望有时间的时候优化一下。

**Comment by 7Sageer** [comment]
已经修复，目前解决方法是简单的将github规则列在微软前面，请拉取最新版本

**Comment by Ocean-TXT** [comment]
感谢及时更新 谢谢
