### ISSUE TITLE
机场订阅bug 和优化建议

### ISSUE THREAD

**Issue by Teda9** [7Sageer/sublink-worker#25]
前提说明，我在绵阿羊基础上，让GPT帮我修改了一版本自用类似的转换工具。
对比过后说出我的一些感受和建议。

1.bug反馈，用两个机场，或者机场跟自建混合填写的时候，输出的 xray 信息并没有把机场的节点链接转换出来，而是直接把两个机场的链接格式变成了base64 的格式。 就是说把链接做了base64转换， 没有把节点提取出来再混合输出。
2. 修改自建节点或者机场之后，重新生成的shorter 链接会变，但是，这个是自用的多， 建议不用频繁修改这个shorter 的ID ，能自定义不改动的就好。
3. 自建跟机场的混合可以做个分开，一个 脚本三个用法。自建 ，机场， 自建+机场。
4.避免被扫出来， 加个密码登录验证，或者链接进入需要token信息。 ?token=1234 这种符合才能进入。（比如需要改动就变更这个密码，原先的链接就失效，而不是，更新一次就被动失效）

![image](https://github.com/user-attachments/assets/28e0cf3a-1620-4a88-9884-e9cf86f014da)

上图是我在用的简单页面。三个链接是固定的base64 链接， 我在用的clash 和sing-box 格式是自己在这个base64转换的。这个页面更新之后，我的固定链接能获取更新，而不是输入一个新的链接。

**Comment by Teda9** [comment]
![image](https://github.com/user-attachments/assets/bae7482a-330d-44f4-82c3-c0120dbd8c3a)
我登录进去我的页面，能显示我的链接，或者我的链接是不变的，你这个不能看到获取到自己的链接。
算是缓存丢失的状态。

**Comment by 7Sageer** [comment]
感谢反馈，关于您提到的几个问题，第一个问题现在已经修复，可以拉取最新版本修复

关于下面的几个问题，我的看法是这样的：

- 2，4其实说的是一件事：相对于获取节点信息而言，扫某个站点的随机路径成本相对较高，往往得不偿失。不过你提到的自定义固定短链确实是一个很好的想法。但是就像上面说的目前看来没有单独设置token的必要。

- 对于第3点，我有段时间没用机场了所以不太了解这会带来什么便利，能提供更详细的思路吗？

**Comment by Teda9** [comment]
> 感谢反馈，关于您提到的几个问题，第一个问题现在已经修复，可以拉取最新版本修复
> 
> 关于下面的几个问题，我的看法是这样的：
> 
> * 2，4其实说的是一件事：相对于获取节点信息而言，扫某个站点的随机路径成本相对较高，往往得不偿失。不过你提到的自定义固定短链确实是一个很好的想法。但是就像上面说的目前看来没有单独设置token的必要。
> * 对于第3点，我有段时间没用机场了所以不太了解这会带来什么便利，能提供更详细的思路吗？

第三点主要实现的就是聚合管理，多个机场跟自建链接统一管理。实际使用场景可能有限，我现在也是用自建节点多了。
我开始分开这三个主要是那时候机场多， 有几个高质量机场，几个垃圾一点的机场，机场多的话到最后混在一起就会导致数据较大。
那时候还对机场分组，收费高质量机场一组，免费低质量机场一组。闲时用低质量机场， 忙时用高质量机场。
现在用自建多了，也是用某一两个节点多，其他节点或者机场使用场景几乎没有了。可能聚合管理还不如分机场管理更便捷。
这点估计可以忽略了。

**Comment by 7Sageer** [comment]
已经添加自定义固定短链功能，请拉取最新版本
