### ISSUE TITLE
使用小火箭复制vmess生成的订阅没办法导入

### ISSUE THREAD

**Issue by pcorvoh** [7Sageer/sublink-worker#28]
使用小火箭复制vmess生成的订阅没办法导入，因为小火箭链接格式为
`MzguMTcyLjY0OjIyODc4?remarks=US-%E5%AE%B6%E5%AE%BD-%E5%8D%95AFF-%E5%B9%BF%E6%B8%AFBGP&obfs=none&alterId=0`
包含了一些vmess的参数，不知道是否可以支持，而且不能对现有的short link进行更改，无法直接修改链接，只能前往cf上的kv上修改

**Comment by 7Sageer** [comment]
我目前对苹果系的代理工具不太熟悉，也没有合适的设备进行测试
就我个人而言，恐怕难以完成这部分内容，但非常欢迎您或其他对此感兴趣的人提交PR来补充这方面的信息。
如果您决定这样做，并在过程中遇到任何问题，请务必与我联系。我很乐意提供可能的帮助或建议。
