### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by kwokzito** [7Sageer/sublink-worker#3]
有考虑制作成docker镜像吗？

**Comment by 7Sageer** [comment]
很好的建议，我会尽快添加更多部署方式。敬请关注。

**Comment by kwokzito** [comment]
你好，郭子涛已收到邮件！

**Comment by 7Sageer** [comment]
我想了一下，因为这个项目主要是面向CloudFlare Workers的，所以构建出的镜像其实比较臃肿而且效率较低，不太适合作为部署环境使用。如果你有这方面的需求，可以自行构建，或者寻找其他类似替代项目。
