### ISSUE TITLE
请求链接

### ISSUE THREAD

**Issue by greatcoolge** [7Sageer/sublink-worker#30]
如果我有一个base64订阅，想转换成singbox请求头参数怎么写?

**Comment by 7Sageer** [comment]
如果你不太清楚一些参数或配置，你可以按照下面的方法进行订阅转换：
- 点击部署按钮根据引导部署并访问你的站点。或者直接访问示例站点[sublink-worker.seven7-ade.workers.dev/](https://sublink-worker.seven7-ade.workers.dev/)
- 粘贴你的base64订阅链接，点击“convert”
- 复制下方生成的Singbox link，导入客户端即可

如果有其他问题，欢迎继续提出
