### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by sztuxp** [7Sageer/sublink-worker#31]
首先，感谢开源的这个项目，确实好用。另外下面几个小建议供参考：
一般用户不会同时要三种订阅连接，建议界面改为下拉选择之类：xray ,sing-box, clash，然后下面用两个连接框，一个长连接，一个短连接，短连接框建议可以固定或随机，如果短连接框有字符串，则表示用户固定，生成后，如果KV存在，就更新相关的KV值就可以了。

**Comment by 7Sageer** [comment]
感谢你的反馈，下面是我个人的看法：

> 一般用户不会同时要三种订阅连接，建议界面改为下拉选择之类

我希望尽可能简化使用这个项目的流程，同时，为有需求的人加入可选的一些高级选项。

我之前也考虑过是否需要向你说的那样修改，但是想了以后觉得下拉列表并不能简化操作流程（最直观的例子就是用户大概率会多点击一下）。相较而言，通过直接列出转换后的所有链接，占用可以接受的页面空间似乎是更好的选择。

> 短连接框建议可以固定或随机，如果短连接框有字符串，则表示用户固定

这个建议很好，之前也有人（ #25 ）提出了类似的观点，有这个功能确实会方便很多。但是最近我个人时间不太够所以还没动。

**Comment by sztuxp** [comment]
感谢！

**Comment by 7Sageer** [comment]
已经添加对应功能，请拉取最新版本
