### ISSUE TITLE
最新版本sing-box客户端用不了

### ISSUE THREAD

**Issue by wb624** [7Sageer/sublink-worker#32]
![Screenshot_20240913-135113_(1)](https://github.com/user-attachments/assets/b11ae97a-fe5b-4e55-be00-bc4dc0ff803e)

**Comment by 7Sageer** [comment]
刚刚使用sing-box 1.9.4测试正常，这应该是Google Play上的最新版本。

对于SingBox，在首次启动时会使用`⚡ 自动选择`的节点（往往是延迟最低的节点）自动下载来自[Github上游仓库](https://github.com/lyc8503/sing-box-rules)的规则集，你提供的截图表明了下载规则出现了一些问题。我认为你可能需要排查该节点到Github的网络连接。

鉴于你没有给出更详细的信息，你可以排查本地节点到GitHub连接的问题: 例如，GitHub不支持IPV6，你的节点是否是IPV6单栈？

**Comment by wb624** [comment]
你好，我用的是最新的beta版本
![Uploading Screenshot_20240914-204517.png…]()

**Comment by wb624** [comment]
![Screenshot_20240914-204517](https://github.com/user-attachments/assets/09298b30-f885-4a6c-9d5f-738400a5e614)

**Comment by 7Sageer** [comment]
你提供的截图表明这应该是网络问题

可以考虑看看如果切换到稳定版能否复现？

**Comment by wb624** [comment]
谢谢大佬的耐心回答，我反复测试了app，代理节点之后，可能是我的节点有问题，跟大佬的项目无关！
