### ISSUE TITLE
生成的短连接，点clear form后，去后台查看所有的KV都在，但点击短连接，显示 “not found”

### ISSUE THREAD

**Issue by sztuxp** [7Sageer/sublink-worker#33]
这个是程序本来的逻辑吗？如果是本来的逻辑，应该也要清除后台KV值比较合适。另外，包括以前生成的数据，KV值都在，但也都不能用了

**Comment by 7Sageer** [comment]
Clear form的作用仅仅是清除缓存在本地的表单数据，不会清除KV。
这个项目最初是个人使用所以没有考虑清除KV的问题，事实上短链生成不会造成很大的KV开销（昨天看了首页万人骑的公共站点也只有几百K的数据）。
如果您比较介意这方面，可以在后台手动清除。

> 另外，包括以前生成的数据，KV值都在，但也都不能用了

你刚刚说的这个下了我一跳，但是实验了发现没有这个问题，短链接也可以正常使用应该是你那边的问题

**Comment by sztuxp** [comment]
我是通过后台修改KV值键值来固定短连接的值，难道是这个影响吗？

**Comment by 7Sageer** [comment]
这个就不太清楚了，不过我会在这几天加上对固定短链接的支持

**Comment by sztuxp** [comment]
非常抱歉，是我自己连接的问题！和项目无关
