### ISSUE TITLE
bug反馈  key “cipher” missing

### ISSUE THREAD

**Issue by Teda9** [7Sageer/sublink-worker#35]
![image](https://github.com/user-attachments/assets/bfa24577-64b5-43be-8a76-ea41e9f506d1)
clash 的模式报错， 用不用Advanced Options 都报错。
怀疑是某个 节点 写的 cipher: none 导致的， 不过修改成 cipher: auto 也还是同样报错。

**Comment by 7Sageer** [comment]
感谢反馈，请问你用的什么协议

**Comment by Teda9** [comment]
用的协议挺多的， vless vmess  Trojan  hy2 tuic5  .
经过我把多个链接测试，终于测试出报错的 协议了。 就一条。
vmess://{"add":"隐藏IP","aid":"0","host":"www.bing.com","id":"d1264208-811c-46c3-a0a8-33e0bd1e5616","net":"ws","path":"d1264208-811c-46c3-a0a8-33e0bd1e5616-vm","port":"2095","ps":"vm-c-US","tls":"","type":"none","v":"2"}

我把IP 隐去了。
我单独测试我的这个节点，是能用的。我也测试了一下，把隐藏IP 更换一下，一样是调取错误。

**Comment by 7Sageer** [comment]
根据你提供的链接成功复现了这个问题，但是实测下来直接添加cipher: auto是可以成功导入的。

于是根据这个尝试修复了这个问题，测试下来可以解决导入的问题。

**Comment by Ocean-TXT** [comment]
点赞
