### ISSUE TITLE
VLESS轉換後提示Internal Server Error？

### ISSUE THREAD

**Issue by haofan170** [7Sageer/sublink-worker#36]
如題，我看支持vless啊，是我哪裡搞錯了麼？ HY2可以正常用
![image](https://github.com/user-attachments/assets/91fca12e-a97f-4534-9334-b600bf67712f)

**Comment by 7Sageer** [comment]
这样的错误是不符合预期的，应该是在处理节点url时遇到了某些边缘情况导致错误

请将脱敏后的节点url发送给我，以便我能进一步了解并解决这个问题

**Comment by haofan170** [comment]
> 这样的错误是不符合预期的，应该是在处理节点url时遇到了某些边缘情况导致错误
> 
> 请将脱敏后的节点url发送给我，以便我能进一步了解并解决这个问题

email了

**Comment by shangdev** [comment]
@haofan170 @7Sageer 请问解决了吗，我也是这个问题。vless格式如下：
vless://YXV0bzpmZjg5ZANDUuNjIuMTE3LjQ6NTQ3ODg?remarks=BWG-reality&obfs=none&tls=1&peer=www.amazon.com&xtls=2&pbk=0ofTxK8Kum2JiaCN59MKEmDPWNcVA&sid=88
