### ISSUE TITLE
http/https 订阅链接 带自定义端口号的无法获取到节点信息

### ISSUE THREAD

**Issue by fyczx** [7Sageer/sublink-worker#37]

**Comment by fyczx** [comment]
代码部署到worker上带自定义端口号的订阅链接无法获取节点信息，在本地部署测试是没有问题能正常获取的。提交到worker有个提醒说是fetch会忽略端口号，不知道是不是这个原因。

**Comment by 7Sageer** [comment]
关于你提到的问题，我参考了以下内容：

https://developers.cloudflare.com/workers/platform/known-issues/#custom-ports

https://github.com/cloudflare/workers-sdk/issues/1320

你的观察应该是正确的，Cloudflare Worker fetch API与标准浏览器或Node.js环境中的fetch不同，可能会忽略端口号。因此在本地测试时可能看不到这个问题。

这不是项目代码的问题，而是Cloudflare Workers平台的特性。
