### ISSUE TITLE
转换vmess节点的时候name会乱码

### ISSUE THREAD

**Issue by imsoosa** [7Sageer/sublink-worker#38]
以这个节点为例：
vmess://eyJ2IjoiMiIsInBzIjoi8J+HuPCfh6wg5paw5Yqg5Z2hMjVUR+mikemBk0BDaXRpemVuU2N5dSIsImFkZCI6ImhrbHMyLmZvcmxpdmUubGl2ZSIsInBvcnQiOiIyMDUzIiwidHlwZSI6Im5vbmUiLCJpZCI6IjNlNzhhNDAwLTBjNzQtNDI1NS04OWFmLWZmMjEwNjNlMjhhNiIsImFpZCI6IjAiLCJuZXQiOiJ3cyIsInBhdGgiOiIvIiwiaG9zdCI6InNnbHMuZm9ybGl2ZS5saXZlIiwidGxzIjoidGxzIn0=

转换后内容如下：
- name: "ð\x9F\x87¸ð\x9F\x87¬ æ\x96°å\x8A\_å\x9D¡25TGé¢\x91é\x81\x93@CitizenScyu" type: vmess server: hkls2.forlive.live port: 2053 uuid: 3e78a400-0c74-4255-89af-ff21063e28a6 alterId: 0 cipher: auto tls: true servername: '' network: ws ws-opts: path: / headers: Host: sgls.forlive.live

可以看到其中的name是乱码

正确的节点信息如下：
- {name: 🇸🇬 新加坡25TG频道@CitizenScyu, server: hkls2.forlive.live, port: 2053, type: vmess, uuid: 3e78a400-0c74-4255-89af-ff21063e28a6, alterId: 0, cipher: auto, tls: true, skip-cert-verify: false, network: ws, ws-opts: {path: /, headers: {Host: sgls.forlive.live}}, udp: true}

**Comment by 7Sageer** [comment]
已修复，请拉取最新版本
