### ISSUE TITLE
节点名称加一个小国旗

### ISSUE THREAD

**Issue by zylf00** [7Sageer/sublink-worker#39]
之前用的订阅转换会自动识别ip国家，在节点名称加入一个小国旗，感觉非常好用，希望加入这个功能
![微信截图_20240924115125](https://github.com/user-attachments/assets/236503ed-7608-4f64-ae96-74aa4c7fe1df)

**Comment by 7Sageer** [comment]
感谢反馈，关于这个，（#19）其实也有提到过类似问题。

最早设计的时候其实并没考虑这个问题，不过最近可能会添加这类功能。目前考虑是在`Advanced Options`中添加一个”按国家分类“的选项

**但是不会在每个节点名称前添加国旗的emoji**，因为这不是普遍需求（例如，某些人的节点信息已经包含了国旗），应该也不会考虑加入对应可选项，因为会加大操作难度

因此如果你有这样的需求，可以在转换前在节点中添加对应信息，或者直接把转换完成的内容发送给ChatGPT让它帮你改。

> 之前用的订阅转换会自动识别ip国家

据我所知目前大部分订阅转换应该只会根据节点名称匹配对应地区（例如：如果名称包含美国，US等信息，就将其归类为美国节点）

未来也多半会采取这种方式进行匹配（如果调用API可能会涉及请求超时等问题）

如果有其他问题，欢迎继续提出
