### ISSUE TITLE
似乎有 bug

### ISSUE THREAD

**Issue by jaydong2016** [7Sageer/sublink-worker#4]
singbox，clashmeta 都会这样
![Screenshot_2024-08-21-14-48-16-793_io nekohasekai sfa](https://github.com/user-attachments/assets/dcfdfa8e-deba-4125-a636-ef19a31a400e)

**Comment by 7Sageer** [comment]
已复现，正在修复，感谢反馈

**Comment by 7Sageer** [comment]
现在应该没问题了，请拉取最新版本。如果有问题欢迎继续反馈。

**Comment by jaydong2016** [comment]
singbox 正常了，
![Screenshot_2024-08-21-16-37-25-492_io.nekohasekai.sfa.jpg](https://github.com/user-attachments/assets/11e77810-185a-4ee2-b296-6d6b73207e71)

clash 那边策略组好像没出来不完整？
![Screenshot_2024-08-21-16-37-05-333_com.github.metacubex.clash.meta.jpg](https://github.com/user-attachments/assets/5544cb4d-c0ce-4c78-8a06-42ecb075d21d)

**Comment by 7Sageer** [comment]
我这边暂时没办法复现你说的clash的问题，鉴于你没有提供更详细的信息，我建议这样做：
- 确认自己的操作正确：例如，我猜测你可能选择自定义规则集但是没有勾选任何规则
- 如果你确信你的操作没有问题，请提供更详细的（脱敏后的）信息，例如：是否使用预定义规则集，有没有自定义规则等信息，勾选了哪些规则等

同时还是非常感谢你的反馈，也欢迎提出更多建议

**Comment by jaydong2016** [comment]
> 我这边暂时没办法复现你说的clash的问题，鉴于你没有提供更详细的信息，我建议这样做：
> - 确认自己的操作正确：例如，我猜测你可能选择自定义规则集但是没有勾选任何规则
> - 如果你确信你的操作没有问题，请提供更详细的（脱敏后的）信息，例如：是否使用预定义规则集，有没有自定义规则等信息，勾选了哪些规则等
> 
> 同时还是非常感谢你的反馈，也欢迎提出更多建议
----

我确实勾选了规则，以下是我搭建网站生成的链接。我的安卓客户端是 clash meta  

https://sb.sbox.us.kg/clash?config=vless%3A%2F%2F2d091acc-9ac9-4934-bea2-44d95c852d7f%40h03.trojan.tel%3A443%3FallowInsecure%3D1%26flow%3Dxtls-rprx-vision%26fp%3Dchrome%26packetEncoding%3Dxudp%26pbk%3DO65wQMagFjmwaaqHOvCzfpAA2-r-xTxwIeYoW066Vzg%26security%3Dreality%26sid%3D48c748ee%26sni%3Ddownload-installer.cdn.mozilla.net%26type%3Dtcp%23%255Bvless%255D%25F0%259F%2587%25AF%25F0%259F%2587%25B5%2520V103-1X-Tokyo%0D%0Ahysteria2%3A%2F%2F2d091acc-9ac9-4934-bea2-44d95c852d7f%40h01.trojan.tel%3A50193%3Finsecure%3D1%26sni%3Dh01.trojan.tel%23%255BHy2%255D%25F0%259F%2587%25B0%25F0%259F%2587%25B7%2520H101-1X-Chuncheon&selectedRules=%5B%22AI%20Services%22%2C%22Youtube%22%2C%22Google%22%2C%22Telegram%22%5D&customRules=%5B%5D

**Comment by 7Sageer** [comment]
你的订阅链接没有问题，另外网站工作似乎也正常，我尝试在安卓的最新版本clash meta使用了你的订阅链接，结果如下：

![Screenshot_20240821_com.github.metacubex.clash.meta.jpg](https://github.com/user-attachments/assets/4e38dd9c-ee1e-48d9-801d-692b285811a6)

看上去没有任何问题，我认为这可能是客户端的问题，你应该确保你的订阅正确更新，或者新创建一个订阅。

另外，你刚刚暴露了你的订阅链接，这意味着任何看到链接的人都能白嫖你的节点，我会稍候删除你的回复，必要的话，可以修改节点信息确保安全。

**Comment by 7Sageer** [comment]
最近也有人提到这个问题，目前看下来，对于clashmeta for Android，高于[v2.10.1]版本会出现不显示规则集的问题，目前原因尚不清楚。我会尽快修复这个问题，感谢反馈。

**Comment by jaydong2016** [comment]
> 最近也有人提到这个问题，目前看下来，对于clashmeta for Android，高于[v2.10.1]版本会出现不显示规则集的问题，目前原因尚不清楚。我会尽快修复这个问题，感谢反馈。

好像是调用本地 geo 数据的问题，meta 内核已经支持类似 singbox 的 srs 格式的 ruleset，可以不需要使用 geo 了
