### ISSUE TITLE
能不能弄一个视频教程

### ISSUE THREAD

**Issue by bbylw** [7Sageer/sublink-worker#45]
Deploy to Cloudflare Workers 不知道要怎么操作啊，
有文图教程也行

**Comment by 7Sageer** [comment]
请查看[FAQ文档](https://github.com/7Sageer/sublink-worker/blob/main/doc/FAQ.md)：我尝试写了一个简短的教程。

如果有任何问题，请务必提交issue，这样也可以协助完善这份文档。
