### ISSUE TITLE
一键部署更新

### ISSUE THREAD

**Issue by Ocean-TXT** [7Sageer/sublink-worker#5]
你好，我是个小白，看到您有更新，我是使用的一键部署，请问我该如何更新喃，我的github已经更新了内容 但是CF上并没有更新

**Comment by 7Sageer** [comment]
感谢你的跟进，正常来说，如果已经在GitHub中sync fork，是可以正确更新的。
如果你确认无法正确更新，可以使用下面的方法手动更新：

- 在你fork的仓库中，在顶栏中找到`Actions`并点击进入
- 在侧栏中`Deploy Worker`工作流并点击进入
- 点击`Run workflow`并运行，等待工作流运行完毕即可

如果你发现这个方法无法解决问题，或者有新的问题，欢迎继续反馈。

**Comment by Ocean-TXT** [comment]
谢谢你能这么快速的回复我，原因我找到了，是因为当时创建的时候TOKEN设置了有效期，过期了，所以sync fork造成无法更新。 另外我发现了Tuic节点转换为clash订阅后不可用，研究后发现是因Tuic的clash订阅不完整，情况如下

- name: /
    type: /
    server: /
    port: /
    uuid: /
    password: /
缺少了下面信息（转换后的订阅中节点信息只有上面的信息，添加下面的信息到clash订阅里面后就好了)
    alpn: [h3]
    disable-sni: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
    sni: www.bing.com
    skip-cert-verify: true

因为是小白所以不知道是什么原因造成的，还望有时间的时候测试一下。感谢。

**Comment by 7Sageer** [comment]
感谢反馈，关于这个问题，我想确认一下：相同节点下Singbox是否可用？另外，上面是否提供了所有缺失的信息？
因为确实我不太了解TUIC所以当时写转换的时候就是保证我自己测试节点能用就行。

**Comment by Ocean-TXT** [comment]
经测试相同节点下Singbox也不可用，上面已经提供了我所知道的所有缺失.
另外发现在clash订阅连接中包含了缺失内容,但网页打开的内容不包含。  
规则集不可用，我更新部署后发现Clash除了Tuic不可用，规则集也不可用，clash规则中只有 节点选择 一项；sing-box订阅中也缺失规则集。

**Comment by 7Sageer** [comment]
感谢你的反馈和热心的测试。
我推测造成的原因是你在粘贴分享url后，没有点击advanced options进行设置而直接点击转换，而默认选项没有选中任何规则集，导致了你看到的情况。

如果是这样，那么这显然不是你的操作问题，我会尽快修复你指出的bug。在我完成修改前，你可以这样做：
- 粘贴分享url
- 打开advanced options，在下拉菜单中选择非“custom”项
- 点击转换获取订阅链接

如果你认为你遇到的不是这个问题，或者我提供的临时解决方案无法解决你的问题，请提供**脱敏后**的更多信息，例如：你的操作流程，生成的订阅链接等。

**Comment by Ocean-TXT** [comment]
有点击advanced options，并且有勾选所有项目再转换，浏览器内容打开订阅链接有规则集内容，可能是我的CLASH有问题造成的，我换成原来的Clash版本就正常了。

TUIC转换缺少内容的情况，还望有时间修复一下，感谢。

**Comment by 7Sageer** [comment]
高版本Clashmeta的问题现在基本解决了
关于TUIC的问题，我添加了你提到的缺失的部分，但我并不太确定这是否能解决你的问题，因为这边我暂时没有复现出来。
如果这个修改并不能解决你的问题，请将你的配置内容和订阅链接脱敏后发送到seven7@cock.li，以便我进行进一步修改。

**Comment by Ocean-TXT** [comment]
经测试，更新后Tuice节点转换正常可用，谢谢
