### ISSUE TITLE
规则为何没有生效？

### ISSUE THREAD

**Issue by GD2021** [7Sageer/sublink-worker#50]
将转换后的订阅添加到windows客户端，规则没有生效

![image](https://github.com/user-attachments/assets/6757fe4f-eef3-4034-a3bb-431b62a84eda)
![image](https://github.com/user-attachments/assets/988c8f51-703e-4167-afbc-636646152c1c)

**Comment by 7Sageer** [comment]
我注意到你使用了GUI for SingBox， 这个客户端在导入时似乎只会导入节点信息而不会导入路由规则。

你可以更换客户端；或者打开订阅链接并复制对应规则，在GUI for SingBox`策略组设置`与`路由规则设置`等选项处中手动粘贴策略组信息
