### ISSUE TITLE
关于singbox首次启动过慢的问题

### ISSUE THREAD

**Issue by jaydong2016** [7Sageer/sublink-worker#55]
![IMG_20241120_180010.jpg](https://github.com/user-attachments/assets/9ed6c7d9-41ea-4ae3-818f-952cf99b97f7)

之前讨论过的首次启动需要等待几分钟的问题，应该是使用了geosite，且没有指定用于下载 GeoSite 资源的出站的标签导致的。Geosite 很快在接下来的singbox 更新中被移除
https://sing-box.sagernet.org/zh/configuration/route/geosite/

可改为使用ruleset，
示例
https://github.com/chika0801/sing-box-examples/blob/main/Tun/self-use/sing-box_1.10.json

**Comment by 7Sageer** [comment]
感谢提醒，其实在刚开始的时候就注意到不能用geosite的这个问题，其实你也可以看到主要出站规则都是用了ruleset，但是~因为直接抄的别人的dns配置所以~没注意到dns配置使用了geosite，我会尽快解决这个问题。

**Comment by 7Sageer** [comment]
已经完成修改，速度应该会有所提升，可以拉取最新版本
再次感谢您的反馈
