### ISSUE TITLE
转换vless节点时会丢失headers信息

### ISSUE THREAD

**Issue by imsoosa** [7Sageer/sublink-worker#6]
以这个节点为例，转换后ws-opts里的headers: {Host: ml.mcclellandhausbau.com}参数丢失了：

vless://d9ae134b-d225-4f4d-abed-0e3f8f16bd50@36.140.92.97:10346?encryption=none&security=tls&type=ws&host=ml.mcclellandhausbau.com&path=d9ae134b#IT-TalkTalk-Siziano_tls

这是目前转换后的节点配置信息：
proxies:
  - name: IT-TalkTalk-Siziano_tls
    type: vless
    server: 36.140.92.97
    port: 10346
    uuid: d9ae134b-d225-4f4d-abed-0e3f8f16bd50
    tls: true
    client-fingerprint: chrome
    servername: ''
    network: ws
    ws-opts:
      path: d9ae134b
    tfo: false
    skip-cert-verify: false

ws-opts里缺失了 headers: {Host: ml.mcclellandhausbau.com} 会导致连接失败

**Comment by 7Sageer** [comment]
感谢反馈，已经进行响应修改，请拉取最新版本以解决此问题
