### ISSUE TITLE
hy2转换不了

### ISSUE THREAD

**Issue by lsh1215225** [7Sageer/sublink-worker#61]
## 问题描述
描述你遇到的使用问题
hy2节点转换不了
## 环境信息
- 客户端类型(SingBox, Clash等)Flclash
- 客户端版本latest

## 原始节点信息：
使用适当的方式展示未进行订阅转换前的配置，注意脱敏。例如：
- 分享url
- 已隐藏
- Xray/SingBox/Clash 的配置文件

## 操作步骤
1.粘贴
2.转换
3.填url

## 预期行为
提示use or proxies missing

## 尝试过的解决方案
描述你已经尝试过的解决方法

- [x] 我确认没有找到解决相同问题的 issue

**Comment by lsh1215225** [comment]
> 你没有提供你的节点信息，所以没办法具体地分析你的问题，但是根据报错use or proxies missing我推测应该是sublink-worker没有正确识别你的节点，可能是以下原因：
> 
> * 目前不支持以clash/sing-box的形式输入节点信息，你可能以该形式输入
> * 扩展功能的基础配置输入框目前不支持识别节点信息，你应该在最上方输入
> 
> 请提供你脱敏后的节点信息以获取进一步支持

hysteria2://******@***.***.**.*:*****/?insecure=1&sni=www.bing.com#Hysteria2-misaka

**Comment by lsh1215225** [comment]
> 另外就是你早上把订阅链接暴露在这里了一段时间，虽然没有直接暴露节点信息但是别有用心的人可以通过url信息获取你的节点信息。
> 
> 我已经帮你隐藏了。如果在意节点安全的话请尽快更换。

thx~我是用脚本直接生成的节点，然后用你这个转换生成的分享链接

**Comment by 7Sageer** [comment]
刚刚修改了一下，现在直接粘贴hy2链接也可以直接使用了
