### ISSUE TITLE
无效的订阅内容

### ISSUE THREAD

**Issue by HaHaIsMe** [7Sageer/sublink-worker#69]
## 问题描述
清晰简洁地描述 bug

## 环境信息
- 客户端类型(v2rayN)
- 客户端版本：v7.1.3

## 原始节点信息：
使用适当的方式展示未进行订阅转换前的配置，注意脱敏。例如：
- 分享url: https://sublink-worker.xx-xx.workers.dev/xray?config=vless%3A%2F%xxxxxxxxx-e6ac-485a-9481-976a0415eab9%40visa.cn%3A443%3Fencryption%3Dnone%26security%3Dtls%26sni%3Dqwe-dts.pages.dev%26type%3Dws%26host%3Dqwe-dts.pages.dev%26path%3D%253Fed%253D2560%23iSF4u%0Avless%3A%F%2xxxxxxxxx-e6ac-485a-9481-976a0415eab9%40visa.cn%3A443%3Fencryption%3Dnone%26security%3Dtls%26sni%3Dbpb.my79801.com%26type%3Dws%26host%3Dbpb.my79801.com%26path%3D%253Fed%253D2560%23iSF4u%0Avless%3A%2F%xxxxxxxxx-e6ac-485a-9481-976a0415eab9%40visa.cn%3A443%3Fencryption%3Dnone%26security%3Dtls%26sni%3Dv2.yunchun.top%26type%3Dws%26host%3Dv2.yunchun.top%26path%3D%253Fed%253D2560%23iSF4u%0Avless%3A%2F%2xxxxxxxxx-e6ac-485a-9481-976a0415eab9%40visa.cn%3A443%3Fencryption%3Dnone%26security%3Dtls%26sni%3Dmi6-25o.pages.dev%26type%3Dws%26host%3Dmi6-25o.pages.dev%26path%3D%253Fed%253D2560%23iSF4u%0Avless%3A%F%xxxxxxxxx-e6ac-485a-9481-976a0415eab9%40visa.cn%3A443%3Fencryption%3Dnone%26security%3Dtls%26sni%3Dbpb-panel-47v.pages.dev%26type%3Dws%26host%3Dbpb-panel-47v.pages.dev%26path%3D%253Fed%253D2560%23iSF4u%0Avless%3A%2F%xxxxxxxxx-e6ac-485a-9481-976a0415eab9%40visa.cn%3A443%3Fencryption%3Dnone%26security%3Dtls%26sni%3Dbpb-atv.pages.dev%26type%3Dws%26host%3Dbpb-atv.pages.dev%26path%3D%253Fed%253D2560%23iSF4u%0Avless%3A%F%2xxxxxxxxx-e6ac-485a-9481-976a0415eab9%40visa.cn%3A443%3Fencryption%3Dnone%26security%3Dtls%26sni%3Dbpb-panel-a5z.pages.dev%26type%3Dws%26host%3Dbpb-panel-a5z.pages.dev%26path%3D%253Fed%253D2560%23iSF4u%0Avless%3A%F%2xxxxxxxxx-e6ac-485a-9481-976a0415eab9%40visa.cn%3A443%3Fencryption%3Dnone%26security%3Dtls%26sni%3Dwww.opensignal.com.naynay09.dynv6.net%26type%3Dws%26host%3Dwww.opensignal.com.naynay09.dynv6.net%26path%3D%253Fed%253D2560%23iSF4u%0Avless%3A%F%2xxxxxxxxx-e6ac-485a-9481-976a0415eab9%40visa.cn%3A443%3Fencryption%3Dnone%26security%3Dtls%26sni%3Dkjgx20240729bpb.pages.dev%26type%3Dws%26host%3Dkjgx20240729bpb.pages.dev%26path%3D%253Fed%253D2560%23iSF4u%0Avless%3A%2F%2xxxxxxxxx-e6ac-485a-9481-976a0415eab9%40visa.cn%3A443%3Fencryption%3Dnone%26security%3Dtls%26sni%3Dhcy4f8oyvc.asemanvpn.skymobiletm.ir%26type%3Dws%26host%3Dhcy4f8oyvc.asemanvpn.skymobiletm.ir%26path%3D%253Fed%253D2560%23iSF4u%0A
- Xray/SingBox/Clash 的配置文件

## 错误日志
可选，技术条件允许的话建议粘贴完整日志信息
2024/11/30 22:24:51 1130->The remote server returned an error: (409) Conflict.
2024/11/30 22:24:51 1130->无效的订阅内容
2024/11/30 22:24:51 -------------------------------------------------------
2024/11/30 22:24:51 更新订阅结束
## 复现步骤
1.从v2rayN中【导出分享链接到粘贴板Base64编码】如上
2. Convert后生成的Xray Link复制再次导入v2rayN新建分组提示【无效的订阅内容】，生成短链接导入也是【无效的订阅内容】
3.但刚刚建立好时分享链接曾经正常，只是不知什么原因之后一直出错
4.刚刚接触订阅地址搭建，请先进们指正我做错了什么？感谢再感谢……

## 预期行为
描述你期望发生的事情

## 补充信息
添加任何其他有关问题的信息

- [ ] 我愿意提交PR来修复这个问题

- [x] 我提供的信息已经经过脱敏

- [x] 我确认没有找到解决相同问题的 issue

**Comment by 7Sageer** [comment]
你好！根据你提供的信息,我推测可能是因为订阅链接中存在重名节点造成的（参考#34）

这个问题来源于sublink-worker设计伊始的缺陷，我可能会在随后解决这个问题,在问题被彻底修复之前，你可以在V2RayN中更改节点名称来解决。因为已经有类似的issue，这个issue将在随后关闭。

不过一点个人的意见就是如果你使用v2RayN，其实不太需要使用这里的订阅转换功能。
