### ISSUE TITLE
有效的SSR url转换成clash link后，生成的文件里proxies: []

### ISSUE THREAD

**Issue by chenmancm** [7Sageer/sublink-worker#72]
## 问题描述
清晰简洁地描述 bug
有效的SSR url转换成clash link后，生成的yaml文件里没有proxy信息

## 环境信息
- 客户端类型：ClashX Pro (for Mac)
- 客户端版本：1.118.1.1

## 原始节点信息：
未进行订阅转换前的配置是SSR url，在手机小火箭配置后可有效使用

## 复现步骤
1. 导入SSR URL，成功转换clash link
2. 打开生成的clash link，里面proxies: []

![生成的yaml文件](https://github.com/user-attachments/assets/b0b687c5-6683-44e8-b714-59ef4c4cb1cb)

**Comment by 7Sageer** [comment]
感谢反馈，目前sublink-worker不支持SSR协议，也暂时没有支持的计划。因为目前对于GFW而言，SSR安全性较SS几乎没有任何提升，甚至有更明显的特征。在实现上，SS也更加简洁。

建议你将你的节点更换为更安全的协议来获取支持。
