### ISSUE TITLE
无法自动部署

### ISSUE THREAD

**Issue by elfcute** [7Sageer/sublink-worker#73]
## 问题描述
无法自动部署

我的操作：
1、点击start，fork项目
2、点击一键部署按钮，然后再cloudflare复制id和令牌，然后粘贴
![image](https://github.com/user-attachments/assets/0cf46230-5479-4395-b115-a731eeeaaf5d)
![image](https://github.com/user-attachments/assets/1e413483-04d9-4d8b-9f88-ebb86bf0ceac)

![image](https://github.com/user-attachments/assets/4d7b2c99-66c5-4a69-8983-2fcc50a598ec)
3、开启工作流action
![image](https://github.com/user-attachments/assets/f222e159-0b4a-491e-ad72-97f97aad24f7)

4、错误日志：
`Run KV_NAMESPACE="SUBLINK_KV"
Checking for KV namespace: SUBLINK_KV

检查 KV 命名空间：SUBLINK_KV
✘ [ERROR] In a non-interactive environment, it's necessary to set a CLOUDFLARE_API_TOKEN environment variable for wrangler to work. Please go to https://developers.cloudflare.com/fundamentals/api/get-started/create-token/ for instructions on how to create an api token, and assign its value to CLOUDFLARE_API_TOKEN.

🪵  Logs were written to "/home/runner/.config/.wrangler/logs/wrangler-2024-12-07_00-01-35_4[32](https://github.com/elfcute/sublink-worker/actions/runs/12207938815/job/34060260391#step:7:33).log"
Error: Process completed with exit code 1.`
(https://github.com/elfcute/sublink-worker/actions/runs/12207938815/job/34060260391#step:7:33).log"
Error: Process completed with exit code 1.

![image](https://github.com/user-attachments/assets/72aace23-99f4-492f-afdb-bb70acbe91b2)

**Comment by 7Sageer** [comment]
错误的原因在这里：

> ✘ [ERROR] In a non-interactive environment, it's necessary to set a CLOUDFLARE_API_TOKEN environment variable for wrangler to work. Please go to https://developers.cloudflare.com/fundamentals/api/get-started/create-token/ for instructions on how to create an api token, and assign its value to CLOUDFLARE_API_TOKEN.

应该是令牌权限设置错误或者是没有设置令牌导致的。

建议你参考[FAQ文档](https://github.com/7Sageer/sublink-worker/blob/main/docs/FAQ.md#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96-worker-account-id-%E5%92%8C-api-token)从模板创建API Token解决这个问题。

**Comment by elfcute** [comment]
> 错误的原因在这里：
> 
> > ✘ [ERROR] In a non-interactive environment, it's necessary to set a CLOUDFLARE_API_TOKEN environment variable for wrangler to work. Please go to https://developers.cloudflare.com/fundamentals/api/get-started/create-token/ for instructions on how to create an api token, and assign its value to CLOUDFLARE_API_TOKEN.
> 
> 应该是令牌权限设置错误或者是没有设置令牌导致的。
> 
> 建议你参考[FAQ文档](https://github.com/7Sageer/sublink-worker/blob/main/docs/FAQ.md#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96-worker-account-id-%E5%92%8C-api-token)从模板创建API Token解决这个问题。

佬 你这个faq文档如下
![image](https://github.com/user-attachments/assets/91433b56-1745-45ef-a6d1-278968f8e3b8)


但是你看上面的问题的图片中，不就是这两步吗？权限图也有
![image](https://github.com/user-attachments/assets/a3e2969b-5e4d-4518-a763-44b7674e82f2)

**Comment by 7Sageer** [comment]
抱歉好像是workflow出了一些问题，我尝试修改了一下，能否再次运行一下看下问题是否解决？

**Comment by elfcute** [comment]
> 抱歉好像是workflow出了一些问题，我尝试修改了一下，能否再次运行一下看下问题是否解决？

现在可以了 我早上搞了一个小时没搞定，我反复看视频教程，还换了账号，泪目了

**Comment by 7Sageer** [comment]
应该是wrangler更新以后和现有的部署脚本出现了冲突导致的

还是非常感谢你的反馈让我及时发现这个问题
