### ISSUE TITLE
我也遇到了无法自动部署的问题，在部署过程中创建KV出现了问题，我是完全按照API创建向导的方式生成的TOKEN

### ISSUE THREAD

**Issue by alvin820921** [7Sageer/sublink-worker#74]
![image](https://github.com/user-attachments/assets/dc804158-b982-40ea-aa8b-46eb650aded4)

![image](https://github.com/user-attachments/assets/a3c760f1-2459-4104-9951-c5f613f7827c)

**Comment by 7Sageer** [comment]
抱歉好像是workflow出了一些问题，我尝试修改了一下，能否再次运行一下看下问题是否解决？

**Comment by alvin820921** [comment]
KV的问题解决了，可以正常自动部署，谢谢，大佬威武。
