### ISSUE TITLE
服务器 VPS 上部署问题

### ISSUE THREAD

**Issue by loohalh** [7Sageer/sublink-worker#78]
大佬，这个能在服务器 VPS 上部署吗？没有多余的域名了，而且 cf 访问速度也慢，访问也不稳定

**Comment by 7Sageer** [comment]
可以，但是步骤会很繁琐，我不太推荐这样做，建议你还是使用Cloudflare部署然后绑定二级域名（或者之类的）。

如果你有部署服务器的需求，可以优先考虑 [SublinkX](https://github.com/gooaclok819/sublinkX) , 这个项目可以快速部署到docker上。

顺便说一句，建议不要通过未加密的方式部署这类服务（例如直接用ip访问站点），这样会有被中间人攻击的可能性，换句话说，理论上你访问你的VPS经过的所有网关都会知道你的节点信息。如果没有域名，可以自行搜索下ssh转发。

**Comment by loohalh** [comment]
有域名，但是没有托管在国内，没有托管在 cf 上，尝试过 Sublink，还是 你这个简介好用

**Comment by loohalh** [comment]
> 可以，但是步骤会很繁琐，我不太推荐这样做，建议你还是使用Cloudflare部署然后绑定二级域名（或者之类的）。
> 
> 如果你有部署服务器的需求，可以优先考虑 [SublinkX](https://github.com/gooaclok819/sublinkX) , 这个项目可以快速部署到docker上。
> 
> 顺便说一句，建议不要通过未加密的方式部署这类服务（例如直接用ip访问站点），这样会有被中间人攻击的可能性，换句话说，理论上你访问你的VPS经过的所有网关都会知道你的节点信息。如果没有域名，可以自行搜索下ssh转发。

大佬，有个大概的路线么或者步骤指导吗？也为这个项目多一个部署方式呗 [抱拳]
