### ISSUE TITLE
api 如何可以同时多个节点？

### ISSUE THREAD

**Issue by fscarmen** [7Sageer/sublink-worker#8]
看到已经有 Sublink Worker API 文档，感谢大佬的付出啊。

同时我想问问，如果节点有 vless / vmess / trojan / hy2 等等多个，query 应该如何拼接，可否写个示例呢，谢谢！

**Comment by 7Sageer** [comment]
大佬您好，感谢您最开始给出api的建议，也感谢您的持续跟进。

对于多个不同类型节点的组合查询，可在 config 参数中使用 URL 编码的换行符（%0A）来分隔不同的配置信息。
例如要转换以下节点：
```
vless://example1
vmess://example2
trojan://example3
hysteria2://example4
```

将上述内容进行 URL 编码后，将其作为 config 参数的值
即发送以下请求：

```
/singbox?config=vless%3A%2F%2Fexample1%0Avmess%3A%2F%2Fexample2%0Atrojan%3A%2F%2Fexample3%0Ahysteria2%3A%2F%2Fexample4&selectedRules=balanced
```

如果有任何其他问题或者建议，欢迎继续交流。也欢迎您继续跟进。
