### ISSUE TITLE
ios版singbox用转换后的配置，报错

### ISSUE THREAD

**Issue by GD2021** [7Sageer/sublink-worker#81]
![image](https://github.com/user-attachments/assets/c6fda51e-5551-4f37-a2d3-be25cc3ba87e)

配置：
https://www.notes.cloudns.be/01jffd2sakap22ta7d3bngj6hm#87OM4k6-vzmA2CvH7u9udPSuboNRel-cyvtKEyDEBP0

**Comment by 7Sageer** [comment]
看起来是关于出站节点信息的问题，能否提供具体的节点信息到我的邮箱 7sageer@djwcb.cn 以便我能进一步分析？感谢你的反馈！
