### ISSUE TITLE
使用转换服务后无法连接

### ISSUE THREAD

**Issue by skyworldp** [7Sageer/sublink-worker#85]
## 问题描述
使用转换服务后无法连接（ping 超时）

## 环境信息
- 客户端类型 Mihomotarty

## 原始节点信息：
转换前proxies
- { name: '🇭🇰 香港1', type: trojan, server: nb_ae7a7.kaiqsz.com, port: 47119, password: 1dde2fce-094d-4adf-80bb-6f6341645385, udp: true, sni: mm1.redapricotcloud.com, skip-cert-verify: true } 
转换后proxies
- name: 🇭🇰 香港1
    type: trojan
    server: nb_ae7a7.kaiqsz.com
    port: 47119
    password: 1dde2fce-094d-4adf-80bb-6f6341645385
    tls: false
    servername: ''
    network: tcp
    tfo: false   

## 错误日志
可选，技术条件允许的话建议粘贴完整日志信息

## 复现步骤
1.转化格式后丢失部分选项  且不能正常连接 客户端无报错
2.总config里面Mixedport丢失
3.

## 预期行为
能够连接

## 补充信息
添加任何其他有关问题的信息

- [ ×] 我愿意提交PR来修复这个问题

- [ ×？] 我提供的信息已经经过脱敏

- [x] 我确认没有找到解决相同问题的 issue

**Comment by 7Sageer** [comment]
感谢反馈，应该是trojan的参数错误导致的，使用最新版本应该可以连接

然后我会隐藏你的节点信息防止泄露
