### ISSUE TITLE
反馈一下默认选中广告拦截rules的问题

### ISSUE THREAD

**Issue by imsoosa** [7Sageer/sublink-worker#9]
感谢作者的辛苦付出。
反馈个小问题：
在默认未开启Advanced Options的时候，生成的订阅配置文件中默认添加了广告拦截的rules，如下：

rules: 
- GEOSITE,category-ads-all,🛑 广告拦截 
- GEOIP,private,🏠 私有网络 
- GEOSITE,geolocation-cn,🔒 国内服务 
- GEOIP,cn,🔒 国内服务 
- MATCH,🐟 漏网之鱼

但是有挺多客户端使用的是这个Geosite.dat

https://github.com/MetaCubeX/meta-rules-dat

这个Geosite.dat里的最新版本中category-ads-all分组被精简了，“geosite:category-ads-all 仅使用域名作为广告拦截用途作用有限，因此不作额外域名添加”。

所以就会导致一些客户端导入转换后的订阅报错。
是否能够考虑取消默认对category-ads-all的选中。

**Comment by 7Sageer** [comment]
感谢反馈，已经移除了对于category-ads-all的默认选中。
方便的话顺便请教一下，我个人没有专门了解过category-ads-all，所以不太清楚，这个规则是目前已经被广泛弃用了吗？或者说，目前认为作用效果不明显？
如果是的话，可能会考虑未来直接把这部分移除

**Comment by imsoosa** [comment]
因为MetaCubeX在维护mihomo核心，他这么做，应该可以理解为被广泛弃用，因为现在开源的核心除了mihomo就是singbox，用mihome核心的gui很多，目前在更新的很多客户端都是基于mihome核心。

**Comment by 7Sageer** [comment]
好的，晚点我再看看，感谢解答
